### PR TITLE
Update terrestrial.xml

### PR DESCRIPTION
**Pull request by EnoSat**
update:
GI
PLP
Europe (GE06)
SCANDINAVIA (not use this raster in VHF)
SVK

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
The header was added to reflect the scanning options in Enigma2 images at the time.  Are  you sure that the scanning options in most  Enigma2 images have changed to what you are proposing

**Comment by AbuBaniaz** [comment]
Please, can you also put in the space before the trailing slash. Some people's editors don't like it.

**Comment by EnoSat** [comment]
which header?

**Comment by AbuBaniaz** [comment]
Screenshot 2024-04-02 201308

**Comment by EnoSat** [comment]
The given values do not exist for GI (only for Code Rate)
https://www.satbroadcasts.com/news,83,What_is_Guard_Interval_in_DVB_T_and_DVB_T2_systems.html
DVBT does not recognize the concept of Inversion, it is used by DVBS
https://en.wikipedia.org/wiki/DVB-T2#System_differences_with_DVB-T

PS: Most of these parameters are ignored or used by HW default, since current tuners work in AUTO mode, except for system switching

**Comment by Huevos** [comment]
[The values at the top of the xml file are the values used in the enigma code.](https://github.com/OpenViX/enigma2/blob/Developer/lib/dvb/frontendparms.h#L118-L122)

**Comment by Huevos** [comment]
```
	/*
	 * WARNING: do not change the order of these values, they are used to parse lamedb and terrestrial.xml FEC fields.
	 * The values are NOT the same as those in eDVBFrontendParametersSatellite/eDVBFrontendParametersCable
	 * (and it's too late to fix this now, we would break backward compatibility)
	 */
```

https://github.com/OpenViX/enigma2/blob/Developer/lib/dvb/frontendparms.h#L118-L122

**Comment by AbuBaniaz** [comment]
When you resubmit this, it will be good if you have an entry for all regions for Slovakia. We don't need to list every region, just the regions with clashes that don't work for all regions. Otherwise we will end up have to list every single city/mast in the world in the xml file.

I also note that you have used identical UHF channel numbers for different  UHF frequencies. As an example below. 

<transponder centre_frequency="482000000" bandwidth="0" constellation="3" />
<transponder centre_frequency="314000000" bandwidth="0" constellation="3" />

**Comment by EnoSat** [comment]
upsss

**Comment by AbuBaniaz** [comment]
Something is lost in writing

Just to repeat:
There is no need to list every city/mast. If a country has made changes rendering the europe list unusable, create a list for all frequencies in that country.  People can then select their country.  If there are regions which then need to have specific entries, list those so that users can fine tune.

**Comment by EnoSat** [comment]
> ```
> 	/*
> 	 * WARNING: do not change the order of these values, they are used to parse lamedb and terrestrial.xml FEC fields.
> 	 * The values are NOT the same as those in eDVBFrontendParametersSatellite/eDVBFrontendParametersCable
> 	 * (and it's too late to fix this now, we would break backward compatibility)
> 	 */
> ```
> 
> https://github.com/OpenViX/enigma2/blob/Developer/lib/dvb/frontendparms.h#L118-L122 https://github.com/openatv/enigma2/blob/master/lib/dvb/frontendparms.h#L119-L123
> 
> That is why these values are marked in this file. They are NOT the values from EN 300 468.

`    bandwidth:
	0 = 8 MHz
	1 = 7 MHz
	2 = 6 MHz
	3 = Auto (default)
	4 = 5 MHz
	5 = 1.712 MHz (only in T2)
	6 = 10 MHz (only in T2)

    code_rate_{LP,HP}:
	0 = 1/2
	1 = 2/3
	2 = 3/4
	3 = 5/6
	4 = 7/8
	5 = Auto (default)
	6 = 6/7
	7 = 8/9
	8 = 3/5
	9 = 4/5

    system:
	0 = DVB-T
	1 = DVB-T2

    transmission_mode:
	0 = 2K (default)
	1 = 8K
	2 = Auto
	3 = 4K
	4 = 1K
	5 = 16K
	6 = 32K

    guard_interval:
	0 = 1/32
	1 = 1/16
	2 = 1/8 (default)
	3 = 1/4
	4 = Auto
	5 = 1/128
	6 = 19/128
	7 = 12/256

    hierarchy_information:
	0 = None (default)
	1 = 1
	2 = 2
	3 = 4
	4 = Auto

    constellation:
	0 = QPSK
	1 = 16-QAM
	2 = 64-QAM
	3 = Auto
	4 = 256-QAM

    inversion (unusable)
	0 = Off
	1 = On
	2 = Unknown

    physical layer pipe:
	0 = 0 (default)
	x = x (max.255)

    flags:
	1: Network Scan
	2: use BAT
	4: use ONIT
	8: skip NITs of known networks
	This is bitmap and combinations can be used.`

**Comment by Huevos** [comment]
You don't need to list the other values.

Just add one entry that covers your national muxes, not local. There is not enough room for all the local muxes in the world in this file.

If your local muxes are unusual you can add your own file on your receiver in /etc/enigma2.

**Comment by Huevos** [comment]
`It would be ideal to use the national version of XML when choosing a language, but this is almost unrealistic.`

Yes, not realistic. Languages don't belong to countries or muxes.

**Pull request closed without merging**
